spring.application.name=mockeval



spring.datasource.url=jdbc:mysql://localhost:3306/mockeval
spring.datasource.username=root
spring.datasource.password=2275
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

